apiVersion: apps/v1
kind: Deployment
metadata:
  
  name: two-tier-deployment

spec:

  replicas: 3
  selector: 
    
    matchLabels: 
      app: frontend

  template:
    metadata: 
      labels:
        app: frontend

    spec:
      containers:
        - name: frontend-container
          image: aryamansam/two-tier-application:v1.0
          ports: 
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "appUser"
            - name: DB_PASSWORD
              value: "appUser@123"
            - name: DB_NAME
              value: "appData"


